version: 0.2

phases:
  build:
    commands:
      - echo "Creating directory structure for lambda layer..."
      - mkdir -p build/dependencies/python/lib/python3.14/site-packages
      - mkdir -p build/api_router_lambda
      - mkdir -p build/scraper_lambda

      - echo "Installing dependencies from requirements.txt..."
      - pip install -r requirements.txt -t build/dependencies/python/lib/python3.14/site-packages/ --root-user-action=ignore

      - echo "Copying agro lib folder into site-packages..."
      # This copies the contents or the folder itself?
      # "Inside site-packages it should have all the packages in requirements.txt and the agro lib folder"
      - cp -r lib build/dependencies/python/lib/python3.14/site-packages/

      - echo "Creating zip file for the lambda layer..."
      - cd build/dependencies && zip -r ../agro-core-layer.zip python && cd ../..

      - echo "Creating zip file for the api router lambda function code..."
      - cp lib/lambdas/agro_api_router.py build/api_router_lambda/
      - cp -r config build/api_router_lambda/
      - cd build/api_router_lambda && zip -r ../api_router_function.zip . && cd ../..

      - echo "Creating zip file for the scraper lambda function code..."
      - cp lib/lambdas/scrape_event_list.py build/scraper_lambda/
      - cp -r config build/scraper_lambda/
      - cd build/scraper_lambda && zip -r ../scrape_lambda_function.zip . && cd ../..

  post_build:
    commands:
      - echo "Uploading layer zip to S3 bucket..."
      - aws s3 cp build/agro-core-layer.zip s3://agro-dev-ops-031621556164-us-east-2-an/agro-core-layer.zip --region us-east-2

      - echo "Publishing new Lambda layer version..."
      - "LAYER_VERSION_ARN=$(aws lambda publish-layer-version --layer-name agroCore --content S3Bucket=agro-dev-ops-031621556164-us-east-2-an,S3Key=agro-core-layer.zip --compatible-runtimes python3.14 --region us-east-2 --query LayerVersionArn --output text)"
      - "echo New layer version published: $LAYER_VERSION_ARN"

      - echo "Updating Lambda function code..."
      - aws lambda update-function-code --function-name ScrapeEventList --zip-file fileb://build/scrape_lambda_function.zip --region us-east-2
      - aws lambda update-function-code --function-name AgroApiRouter --zip-file fileb://build/api_router_function.zip --region us-east-2

      - echo "Waiting for Lambda function code update to complete before updating configuration..."
      - aws lambda wait function-updated --function-name AgroApiRouter --region us-east-2
      - aws lambda wait function-updated --function-name ScrapeEventList --region us-east-2

      - echo "Updating Lambda function to use the new layer version..."
      - "aws lambda update-function-configuration --function-name AgroApiRouter --layers $LAYER_VERSION_ARN --region us-east-2"
      - "aws lambda update-function-configuration --function-name ScrapeEventList --layers $LAYER_VERSION_ARN --region us-east-2"
