scraper:
  default: agro
fetcher:
  default: playwright
  drission_page:
    max_screenshot_height: 16000
    browser_path: "/opt/bin/headless-chromium"
data_extractor:
  default: openai
image_saver:
  default: s3
  s3:
    bucket: "agro-031621556164-us-east-2-an"
    region: "us-east-2"
    path_prefix: "scrape-screenshots"
    aws_access_key_id_env: "S3_AWS_ACCESS_KEY_ID"
    aws_secret_access_key_env: "S3_AWS_SECRET_ACCESS_KEY"
mysql:
  #host: "proxy-1776094332489-database-1.proxy-co77y8ietxyj.us-east-2.rds.amazonaws.com"
  host: "database-1-instance-1.co77y8ietxyj.us-east-2.rds.amazonaws.com"
  port: 3306
  user: "admin"
  password_env: "AGRO_RDS_PASSWORD"
  database: "aml"
