scraper:
  default: agro
fetcher:
  default: drission_page
  drission_page:
    max_screenshot_height: 16000
    browser_path: ""
data_extractor:
  default: openai
image_saver:
  default: s3
  s3:
    bucket: "agro-031621556164-us-east-2-an"
    region: "us-east-2"
    path_prefix: "scrape-screenshots"
    aws_access_key_id_env: "AWS_ACCESS_KEY_ID"
    aws_secret_access_key_env: "AWS_SECRET_ACCESS_KEY"
  local:
    images_dir: "./images"
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password_env: "AGRO_MYSQL_PASSWORD"
  database: "aml"
